### ISSUE TITLE
Chapter 6 Page 119 Errors in VSC++

### ISSUE THREAD

**Issue by dredgeho** [marcosecchi/unrealshadows-ltol#1]
I'm just starting chapter 6. After adding US_CharacterStats.h file to the visual studio project it gives me 9740 errors.  

I'm not sure how to add the file to Visual Studio. The book does not say how to do it. Below is from page 119:

"Open your IDE and create a file in your UnrealShadows_LOTL | Source | UnrealShadows_
LOTL folder called US_CharacterStats.h (as this is a data structure, you won’t need a .cpp
file)."

I added a header file by right clicking the folder in VSC++ and selecting 'add new item' then I selected header file.  I then renamed it and copied in the code from the book (pdf). The # in the first line of #pragma has red ~ and it lists 9740 errors.  

I went into Unreal Engine and compiled and it will compile but I can't select the data structure when you create a data table. Where it says "select US_CharacterStats from the drop-down menu, as depicted in Figure 6.1:"  It is not there.  I have included a screenshot of vsc++ showing 9740 errors.  

I'm sure it's something simple and easy to fix.  please let me know how to fix this. I'd like to finish this book but now I'm stuck and can't go any further. 

![9740 errors](https://github.com/user-attachments/assets/dba70551-dd52-4e66-9f63-ee33522f1071)

**Comment by dredgeho** [comment]
I fixed it by making a text file in the "\UnrealShadows_LOTL\Source\UnrealShadows_LOTL" directory and then copying all the code into it.  I then generated new visual studio project files by right-clicking UnrealShadows_LOTL.uproject.   Then opening the project in Unreal Editor and finally live compiling.  Now it shows up in the Misc/DataTable.

**Comment by goodlord** [comment]
> I fixed it: First close VSC++ and unreal engine. Make a new text file in the "\UnrealShadows_LOTL\Source\UnrealShadows_LOTL" directory. Paste all the code into this text file. Rename the text file 'CharacterStats.h'. Generate new visual studio project files by right-clicking UnrealShadows_LOTL.uproject. Then open the project in Unreal Editor and finally click live compiling. Now it shows up in the Misc/DataTable.
> 
> This happened again when I made another header file and things that shouldn't be red ~ errors were red like #include. Fixed this by unloading and reloading the project in the right side panel.

I closed visual studio and didn't change anything. Opened it again today (a day later) and it's back. Red squiggly lines all over all the code. I seriously don't understand how anyone can code like this. I know it's not the authors fault but man i wish this book only used blueprints because visual studio is a hot mess.  I just fixed this problem two days ago and did nothing to the code and opened it again and the problem is back.  This is dumb.

**Comment by marcosecchi** [comment]
As stated in my previous message, this is a personal repository and not the official repository for the book.
Opening issues here just creates confusion.

As a side note, the book clearly states that you will need some C++ knowledge in order to fully understand most of the topics. This is not to be considered an "issue" in the project.
